/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AdminLayoutRouteImport } from './pages/admin/layout'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AdminPrimaryStatisticsIndexRouteImport } from './pages/admin/_primary/statistics/index'
import { Route as AdminPrimarySalesIndexRouteImport } from './pages/admin/_primary/sales/index'
import { Route as AdminPrimaryHistoryIndexRouteImport } from './pages/admin/_primary/history/index'
import { Route as AdminPrimaryDashboardIndexRouteImport } from './pages/admin/_primary/dashboard/index'
import { Route as AdminPrimaryCollectionPointsIndexRouteImport } from './pages/admin/_primary/collection-points/index'
import { Route as AdminAccountSettingsIndexRouteImport } from './pages/admin/_account/settings/index'
import { Route as AdminAccountProfileIndexRouteImport } from './pages/admin/_account/profile/index'
import { Route as PublicFaqPrefecturesIndexRouteImport } from './pages/_public/faq/prefectures/index'
import { Route as PublicFaqCooperativesIndexRouteImport } from './pages/_public/faq/cooperatives/index'
import { Route as AdminPrimarySalesSaleIdIndexRouteImport } from './pages/admin/_primary/sales/$saleId/index'
import { Route as AdminPrimaryHistoryCollectIdIndexRouteImport } from './pages/admin/_primary/history/$collectId/index'

const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrimaryStatisticsIndexRoute =
  AdminPrimaryStatisticsIndexRouteImport.update({
    id: '/_primary/statistics/',
    path: '/statistics/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimarySalesIndexRoute = AdminPrimarySalesIndexRouteImport.update({
  id: '/_primary/sales/',
  path: '/sales/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminPrimaryHistoryIndexRoute =
  AdminPrimaryHistoryIndexRouteImport.update({
    id: '/_primary/history/',
    path: '/history/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryDashboardIndexRoute =
  AdminPrimaryDashboardIndexRouteImport.update({
    id: '/_primary/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryCollectionPointsIndexRoute =
  AdminPrimaryCollectionPointsIndexRouteImport.update({
    id: '/_primary/collection-points/',
    path: '/collection-points/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminAccountSettingsIndexRoute =
  AdminAccountSettingsIndexRouteImport.update({
    id: '/_account/settings/',
    path: '/settings/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminAccountProfileIndexRoute =
  AdminAccountProfileIndexRouteImport.update({
    id: '/_account/profile/',
    path: '/profile/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const PublicFaqPrefecturesIndexRoute =
  PublicFaqPrefecturesIndexRouteImport.update({
    id: '/faq/prefectures/',
    path: '/faq/prefectures/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicFaqCooperativesIndexRoute =
  PublicFaqCooperativesIndexRouteImport.update({
    id: '/faq/cooperatives/',
    path: '/faq/cooperatives/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AdminPrimarySalesSaleIdIndexRoute =
  AdminPrimarySalesSaleIdIndexRouteImport.update({
    id: '/_primary/sales/$saleId/',
    path: '/sales/$saleId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminPrimaryHistoryCollectIdIndexRoute =
  AdminPrimaryHistoryCollectIdIndexRouteImport.update({
    id: '/_primary/history/$collectId/',
    path: '/history/$collectId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/faq/cooperatives/': typeof PublicFaqCooperativesIndexRoute
  '/faq/prefectures/': typeof PublicFaqPrefecturesIndexRoute
  '/admin/profile/': typeof AdminAccountProfileIndexRoute
  '/admin/settings/': typeof AdminAccountSettingsIndexRoute
  '/admin/collection-points/': typeof AdminPrimaryCollectionPointsIndexRoute
  '/admin/dashboard/': typeof AdminPrimaryDashboardIndexRoute
  '/admin/history/': typeof AdminPrimaryHistoryIndexRoute
  '/admin/sales/': typeof AdminPrimarySalesIndexRoute
  '/admin/statistics/': typeof AdminPrimaryStatisticsIndexRoute
  '/admin/history/$collectId/': typeof AdminPrimaryHistoryCollectIdIndexRoute
  '/admin/sales/$saleId/': typeof AdminPrimarySalesSaleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/faq/cooperatives': typeof PublicFaqCooperativesIndexRoute
  '/faq/prefectures': typeof PublicFaqPrefecturesIndexRoute
  '/admin/profile': typeof AdminAccountProfileIndexRoute
  '/admin/settings': typeof AdminAccountSettingsIndexRoute
  '/admin/collection-points': typeof AdminPrimaryCollectionPointsIndexRoute
  '/admin/dashboard': typeof AdminPrimaryDashboardIndexRoute
  '/admin/history': typeof AdminPrimaryHistoryIndexRoute
  '/admin/sales': typeof AdminPrimarySalesIndexRoute
  '/admin/statistics': typeof AdminPrimaryStatisticsIndexRoute
  '/admin/history/$collectId': typeof AdminPrimaryHistoryCollectIdIndexRoute
  '/admin/sales/$saleId': typeof AdminPrimarySalesSaleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_public/faq/cooperatives/': typeof PublicFaqCooperativesIndexRoute
  '/_public/faq/prefectures/': typeof PublicFaqPrefecturesIndexRoute
  '/admin/_account/profile/': typeof AdminAccountProfileIndexRoute
  '/admin/_account/settings/': typeof AdminAccountSettingsIndexRoute
  '/admin/_primary/collection-points/': typeof AdminPrimaryCollectionPointsIndexRoute
  '/admin/_primary/dashboard/': typeof AdminPrimaryDashboardIndexRoute
  '/admin/_primary/history/': typeof AdminPrimaryHistoryIndexRoute
  '/admin/_primary/sales/': typeof AdminPrimarySalesIndexRoute
  '/admin/_primary/statistics/': typeof AdminPrimaryStatisticsIndexRoute
  '/admin/_primary/history/$collectId/': typeof AdminPrimaryHistoryCollectIdIndexRoute
  '/admin/_primary/sales/$saleId/': typeof AdminPrimarySalesSaleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/sign-in/'
    | '/sign-up/'
    | '/faq/cooperatives/'
    | '/faq/prefectures/'
    | '/admin/profile/'
    | '/admin/settings/'
    | '/admin/collection-points/'
    | '/admin/dashboard/'
    | '/admin/history/'
    | '/admin/sales/'
    | '/admin/statistics/'
    | '/admin/history/$collectId/'
    | '/admin/sales/$saleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/faq/cooperatives'
    | '/faq/prefectures'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/collection-points'
    | '/admin/dashboard'
    | '/admin/history'
    | '/admin/sales'
    | '/admin/statistics'
    | '/admin/history/$collectId'
    | '/admin/sales/$saleId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/'
    | '/admin/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_public/faq/cooperatives/'
    | '/_public/faq/prefectures/'
    | '/admin/_account/profile/'
    | '/admin/_account/settings/'
    | '/admin/_primary/collection-points/'
    | '/admin/_primary/dashboard/'
    | '/admin/_primary/history/'
    | '/admin/_primary/sales/'
    | '/admin/_primary/statistics/'
    | '/admin/_primary/history/$collectId/'
    | '/admin/_primary/sales/$saleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_primary/statistics/': {
      id: '/admin/_primary/statistics/'
      path: '/statistics'
      fullPath: '/admin/statistics/'
      preLoaderRoute: typeof AdminPrimaryStatisticsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/sales/': {
      id: '/admin/_primary/sales/'
      path: '/sales'
      fullPath: '/admin/sales/'
      preLoaderRoute: typeof AdminPrimarySalesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/history/': {
      id: '/admin/_primary/history/'
      path: '/history'
      fullPath: '/admin/history/'
      preLoaderRoute: typeof AdminPrimaryHistoryIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/dashboard/': {
      id: '/admin/_primary/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminPrimaryDashboardIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/collection-points/': {
      id: '/admin/_primary/collection-points/'
      path: '/collection-points'
      fullPath: '/admin/collection-points/'
      preLoaderRoute: typeof AdminPrimaryCollectionPointsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_account/settings/': {
      id: '/admin/_account/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminAccountSettingsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_account/profile/': {
      id: '/admin/_account/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminAccountProfileIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/faq/prefectures/': {
      id: '/_public/faq/prefectures/'
      path: '/faq/prefectures'
      fullPath: '/faq/prefectures/'
      preLoaderRoute: typeof PublicFaqPrefecturesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/faq/cooperatives/': {
      id: '/_public/faq/cooperatives/'
      path: '/faq/cooperatives'
      fullPath: '/faq/cooperatives/'
      preLoaderRoute: typeof PublicFaqCooperativesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/admin/_primary/sales/$saleId/': {
      id: '/admin/_primary/sales/$saleId/'
      path: '/sales/$saleId'
      fullPath: '/admin/sales/$saleId/'
      preLoaderRoute: typeof AdminPrimarySalesSaleIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_primary/history/$collectId/': {
      id: '/admin/_primary/history/$collectId/'
      path: '/history/$collectId'
      fullPath: '/admin/history/$collectId/'
      preLoaderRoute: typeof AdminPrimaryHistoryCollectIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicFaqCooperativesIndexRoute: typeof PublicFaqCooperativesIndexRoute
  PublicFaqPrefecturesIndexRoute: typeof PublicFaqPrefecturesIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicFaqCooperativesIndexRoute: PublicFaqCooperativesIndexRoute,
  PublicFaqPrefecturesIndexRoute: PublicFaqPrefecturesIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountProfileIndexRoute: typeof AdminAccountProfileIndexRoute
  AdminAccountSettingsIndexRoute: typeof AdminAccountSettingsIndexRoute
  AdminPrimaryCollectionPointsIndexRoute: typeof AdminPrimaryCollectionPointsIndexRoute
  AdminPrimaryDashboardIndexRoute: typeof AdminPrimaryDashboardIndexRoute
  AdminPrimaryHistoryIndexRoute: typeof AdminPrimaryHistoryIndexRoute
  AdminPrimarySalesIndexRoute: typeof AdminPrimarySalesIndexRoute
  AdminPrimaryStatisticsIndexRoute: typeof AdminPrimaryStatisticsIndexRoute
  AdminPrimaryHistoryCollectIdIndexRoute: typeof AdminPrimaryHistoryCollectIdIndexRoute
  AdminPrimarySalesSaleIdIndexRoute: typeof AdminPrimarySalesSaleIdIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountProfileIndexRoute: AdminAccountProfileIndexRoute,
  AdminAccountSettingsIndexRoute: AdminAccountSettingsIndexRoute,
  AdminPrimaryCollectionPointsIndexRoute:
    AdminPrimaryCollectionPointsIndexRoute,
  AdminPrimaryDashboardIndexRoute: AdminPrimaryDashboardIndexRoute,
  AdminPrimaryHistoryIndexRoute: AdminPrimaryHistoryIndexRoute,
  AdminPrimarySalesIndexRoute: AdminPrimarySalesIndexRoute,
  AdminPrimaryStatisticsIndexRoute: AdminPrimaryStatisticsIndexRoute,
  AdminPrimaryHistoryCollectIdIndexRoute:
    AdminPrimaryHistoryCollectIdIndexRoute,
  AdminPrimarySalesSaleIdIndexRoute: AdminPrimarySalesSaleIdIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
